- .env.test
- spec/rails_helper.rb
removes reference to an environment variable I use in the parent project this stemmed from.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
> remove TICKETMASTER_API_KEY env variable

- app/controllers/api/v1/github_repos_controller.rb
The github API calls are authorized and have a huge limit. This is fine to remove user sign in delay tactic.
> remove user validation from this resource

- config/database.yml
Our production DB uses DATABASE_URL to connect, and thus these other settings are leftovers and are potentially confusing later.
`DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"`
> removed unneeded configuration

- app/models/github_repo.rb
- app/serializers/github_repo_serializer.rb
- spec/interactors/users/create_spec.rb
- spec/requests/api/v1/github_repos_spec.rb
Stop parsing stargazers, it's the same thing as watchers.
> watchers and stargazers are the same thing. ugh

- spec/cassettes/GithubRepo/validations/1_1_3.yml
- spec/models/github_repo_spec.rb
Validation tests were making real call to github, this provides cassette to elimination that.
> provide cassette for the validations

- app/apis/crypto_exchanges/base_api.rb
- app/apis/crypto_exchanges/binance_api.rb
- app/models/crypto_exchanges/result.rb
- spec/apis/crypto_exchanges/base_api_spec.rb
- spec/apis/crypto_exchanges/binance_api_spec.rb
Kicking Pinny's tests off with a few examples. Also moved the CryptoExchangeResult class into models.
> Testing kick off

- config/routes.rb
- spec/requests/health_check_spec.rb
It's normal for apps to have monitoring endpoints for various reasons. I'm planning on experimenting with pingdom or perhaps having the front end "wake" the back end on landing page load.
> create health_check endpoint

- config/initializers/sunny_sorter.rb
> capitalized csv for some reason

- config/initializers/sunny_sorter.rb
> removed initializer code

- db/migrate/20220318020359_create_sunny_episode_user_rankings.rb
> removed index so I can get his merged, will fix

- config/initializers/sunny_sorter.rb
> put back the initializer code

- app/controllers/api/v1/sunny_episode_user_rankings_controller.rb
- app/controllers/api/v1/sunny_episodes_controller.rb
- app/models/sunny_episode.rb
- db/seeds/sunny_sorter.rb
- spec/factories/sunny_episode_user_rankings.rb
- spec/factories/sunny_episodes.rb
- spec/models/sunny_episode_spec.rb
> Sunny sorter pass 2

- .github/workflows/deploy.yml
Adds a deployment action so we can autodeploy still.
> created deploy action

- spec/requests/api/v1/sunny_episodes_spec.rb
- spec/swagger_helper.rb
- swagger/v1/swagger.yaml
> repaired failing schema definition syntax

- .github/dependabot.yml
Adds a Dependabot config for management of behavior
> adds dependabot configuration file

- config/initializers/sentry.rb
adds configuration to limit sentry to production
> adds configuration to limit sentry to production

- .env.test
- config/initializers/dotenv.rb
CloudinaryAPI env var for test causing collision and issues
> removed invalid coudinary endpoint

- Gemfile.lock
- app/serializers/user_serializer.rb
- config/initializers/sidekiq.rb
- spec/requests/api/v1/users_spec.rb
> minor tweaks to support front end

- app/controllers/api/v1/sunny_episodes_controller.rb
- app/interactors/sunny_episodes/index.rb
- app/models/sunny_episode.rb
- spec/interactors/sunny_episodes/index_spec.rb
- spec/models/sunny_episode_spec.rb
> update to top 100

- .github/workflows/tests.yml
- app/controllers/api/v1/sunny_episode_user_rankings_controller.rb
- app/models/github_repo.rb
- app/models/sunny_episode.rb
- db/migrate/20230220044307_add_indexes_to_sunny_episodes.rb
- db/schema.rb
- spec/models/sunny_episode_spec.rb
- spec/requests/api/v1/sunny_episode_user_rankings_spec.rb
Proposed changes
Makes the random two method only able to return episode the user hasn't seen in combination before. Adds indexes for performance.
> debugging and performance imrpovements
